### ISSUE TITLE
getting blank screen when i click on project1

### ISSUE THREAD

**Issue by ssamaji** [pumano/allure-reports-portal#1]
Hi i am getting blank screen when i click on project1. can anyone help here. please find below details and project folder structure

Thanks

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): src/**/* uploads/**/* config/**/*
[nodemon] watching extensions: ts,json
[nodemon] starting `ts-node ./src/main.ts`
project: project1 loaded
project: project2 loaded
project: youranotherproject loaded
GET /project1/ 304 4.738 ms - -
GET /project1/styles.css 304 4.081 ms - -
GET /project1/app.js 304 5.535 ms - -
GET /project1/plugins/screen-diff/styles.css 304 2.319 ms - -
GET /project1/plugins/behaviors/index.js 304 2.161 ms - -
GET /project1/plugins/packages/index.js 304 2.073 ms - -
GET /project1/plugins/screen-diff/index.js 304 2.104 ms - -

![image](https://user-images.githubusercontent.com/26387897/93450030-174ec100-f8f3-11ea-8899-c84a03b9a177.png)

![image](https://user-images.githubusercontent.com/26387897/93450108-31889f00-f8f3-11ea-8180-a043ec2209ba.png)

**Comment by pumano** [comment]
@ssamaji did you put your allure report index.html and other files inside project1?

**Comment by ssamaji** [comment]
Yes, this is my project file structure
![image](https://user-images.githubusercontent.com/26387897/93459425-4e2ad400-f8ff-11ea-9f2e-ade2ca94c12e.png)

**Comment by pumano** [comment]
You should copy all files and folders from allure result and put it in project1 folder.

Your project1 folder should contain all the files and folders from allure results

**Comment by ssamaji** [comment]
Working after coping all the files in project1.

Thanks a lot !!!
