### ISSUE TITLE
displaying more than last report generated

### ISSUE THREAD

**Issue by michalw666** [pumano/allure-reports-portal#3]
Hello. Is there a plan to develop a possibility to display more than only the latest report generated for specific project?

**Comment by pumano** [comment]
@michalw666 What do you mean? You want allure result history?

**Comment by michalw666** [comment]
I mean displaying more builds' results for project, not only the latest one, so I can see the details for past builds.

**Comment by pumano** [comment]
try to use this: https://github.com/pumano/allure-reports-portal#allure-reports-with-history-trends

**Comment by michalw666** [comment]
Do you have working example of https://github.com/pumano/allure-reports-portal#allure-reports-with-history-trends ? From description I understand it's only about history trends. I mean the availability of same details for previous builds as for the latest one.

**Comment by pumano** [comment]
@michalw666 sorry for delay, it's looks like you need to create history trends: https://stackoverflow.com/questions/50376630/allure-reports-to-see-historic-trends
then update it after each test run

allure jenkins plugin create it under the hood, but if you use gitlab and use allure-report-portal you should process it manually

**Comment by michalw666** [comment]
Yes, I know what history trends are (and I have it inplemented), but this is not what I'm asking for. In history trends you don't have a look into deep details of previous runs. Anyway, thank you for the reply.
